name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thanks for taking the time to report a bug! This helps us improve the toolkit.

  - type: dropdown
    id: framework
    attributes:
      label: Affected Framework
      description: Which framework is experiencing the issue?
      options:
        - Inverse Precision Framework
        - Optical Depth Enhancement
        - Chromostereopsis Analysis
        - 3D Iris Structure Analysis
        - Post-Quantum Cryptography
        - Herschel-Bulkley Rheology
        - Multi-Phase Flow Analysis
        - Java Security Framework
        - Biological Flow Systems
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the bug.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error Message/Traceback
      description: Please provide any error messages or stack traces.
      render: shell

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: Which Python version are you using?
      options:
        - Python 3.8
        - Python 3.9
        - Python 3.10
        - Python 3.11
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Ubuntu 20.04, macOS 12.0, Windows 11
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - Related issues
        - Screenshots
        - Performance impact
        - Workarounds tried

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply.
      options:
        - label: I have searched for similar issues in the repository
        - label: I have provided a minimal reproducible example
        - label: I have included all relevant error messages
        - label: I have tested with the latest version
